updated github workflows

diff --git a/.github/workflows/nginx.yml b/.github/workflows/nginx.yml
--- a/.github/workflows/nginx.yml
+++ b/.github/workflows/nginx.yml
@@ -13,31 +13,45 @@ jobs:
     runs-on: ubuntu-latest  # Specifies the OS for the job
 
     steps:
+      - name: Deploy to server
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.SERVER_IP }}
+          username: ${{ secrets.SERVER_USER }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          port: 22
+          script: |
+            git pull
+            docker build -t nginx .
+            docker start -d -p 80:80 --name nginx_container nginx
+            
+
       # Step 1: Checkout the code
-      - name: Checkout code
-        uses: actions/checkout@v2
+      # - name: Checkout code
+      #   uses: actions/checkout@v2
 
-      # Step 2: Set up Docker Buildx (for building Docker images)
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
+      # # Step 2: Set up Docker Buildx (for building Docker images)
+      # - name: Set up Docker Buildx
+      #   uses: docker/setup-buildx-action@v2
 
-      # Step 3: Build the Docker image from the Dockerfile
-      - name: Build Docker image
-        run: |
-          docker build -t nginx .
+      # # Step 3: Build the Docker image from the Dockerfile
+      # - name: Build Docker image
+      #   run: |
+      #     docker build -t nginx .
 
-      # Step 4: Run the Nginx container
-      - name: Run Docker container
-        run: |
-          docker run -d -p 80:80 --name nginx-container nginx
+      # # Step 4: Run the Nginx container
+      # - name: Run Docker container
+      #   run: |
+      #     docker run -d -p 80:80 --name nginx-container nginx
 
-      # Step 5: Check if Nginx is running properly
-      - name: Verify Nginx is running
-        run: |
-          curl -f http://localhost:80 || exit 1
+      # # Step 5: Check if Nginx is running properly
+      # - name: Verify Nginx is running
+      #   run: |
+      #     curl -f http://localhost:80 || exit 1
 
-      # Step 6: Clean up by stopping and removing the container
-      - name: Cleanup
-        run: |
-          docker stop nginx-container
-          docker rm nginx-container
+      # # Step 6: Clean up by stopping and removing the container
+      # - name: Cleanup
+      #   run: |
+      #     docker stop nginx-container
+      #     docker rm nginx-container
+
